# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:UsersADMINbmtt-nc-hutech-2280601362lab-03uiecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


